services:
  # ─────────────────── Infra ───────────────────
  mongodb:
    image: mongo:8.0
    ports:
      - 27017:27017

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.11
    volumes:
      - ./test/functionalTest/mosquittoConf/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./test/functionalTest/mosquittoConf/mosquitto_passwd:/mosquitto/config/mosquitto_passwd:ro
    ports:
      - "1883:1883"

  mosquitto-extra:
    container_name: mosquitto-extra
    image: eclipse-mosquitto:2.0.11
    volumes:
      - ./test/functionalTest/mosquittoConf/mosquitto-extra.conf:/mosquitto/config/mosquitto.conf:ro
      - ./test/functionalTest/mosquittoConf/mosquitto_passwd:/mosquitto/config/mosquitto_passwd:ro
    ports:
      - "1884:1884"

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9092,CONTROLLER://kafka1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG4J_ROOT_LOGLEVEL: "OFF"
      KAFKA_LOG4J_LOGGERS: ""
    logging:
      driver: "none"

  kafka2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093,2@kafka2:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094,CONTROLLER://kafka2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_LOG4J_ROOT_LOGLEVEL: "OFF"
      KAFKA_LOG4J_LOGGERS: ""

  kafkaB:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafkaB
    ports:
      - "9095:9095"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9095,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafkaB:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk


  # ─────────────────── Tests ───────────────────
  tests:
    image: ${TEST_IMAGE_NAME:-telefonicaiot/fiware-orion:ci}
    depends_on: [ mongodb, kafka1, kafka2, kafkaB, mosquitto, mosquitto-extra ]
    environment:
      REPO_ACCESS_TOKEN: ${REPO_ACCESS_TOKEN}
      FT_FROM_IX: ${FT_FROM_IX}
      FT_TO_IX: ${FT_TO_IX}
      CB_NO_CACHE: ${CB_NO_CACHE}
      CB_DATABASE_HOST: mongodb
      KAFKA_HOST: kafka1
      KAFKA_HOST2: kafka2
      MQTT_HOST: mosquitto
    volumes:
      - .:/opt/fiware-orion
    command: >
      build -miqts functional
